// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_dark_boom_levle_8 = "CgkIyK-AzZcGEAIQLA"; // <GPGSID>
        public const string achievement_blue_meadow_clear = "CgkIyK-AzZcGEAIQBQ"; // <GPGSID>
        public const string achievement_blaze_staff_levle_8 = "CgkIyK-AzZcGEAIQKw"; // <GPGSID>
        public const string achievement_level_100_achievement = "CgkIyK-AzZcGEAIQDg"; // <GPGSID>
        public const string achievement_death_gun_levle_8 = "CgkIyK-AzZcGEAIQHQ"; // <GPGSID>
        public const string achievement_achieved_the_first_10000_kills = "CgkIyK-AzZcGEAIQEQ"; // <GPGSID>
        public const string achievement_100_card_draws = "CgkIyK-AzZcGEAIQGQ"; // <GPGSID>
        public const string achievement_flame_ball_levle_8 = "CgkIyK-AzZcGEAIQKA"; // <GPGSID>
        public const string achievement_desert_and_city_clear = "CgkIyK-AzZcGEAIQBw"; // <GPGSID>
        public const string achievement_shooting_star_levle_8 = "CgkIyK-AzZcGEAIQLQ"; // <GPGSID>
        public const string achievement_ice_meadow_clear = "CgkIyK-AzZcGEAIQCA"; // <GPGSID>
        public const string achievement_magnetic_field_levle_8 = "CgkIyK-AzZcGEAIQHw"; // <GPGSID>
        public const string achievement_nuff_gun_levle_8 = "CgkIyK-AzZcGEAIQHA"; // <GPGSID>
        public const string achievement_open_only_4_cards = "CgkIyK-AzZcGEAIQCg"; // <GPGSID>
        public const string achievement_equalizer_levle_8 = "CgkIyK-AzZcGEAIQLw"; // <GPGSID>
        public const string achievement_level_10_achievement = "CgkIyK-AzZcGEAIQDA"; // <GPGSID>
        public const string achievement_repair_levle_8 = "CgkIyK-AzZcGEAIQJQ"; // <GPGSID>
        public const string achievement_first_play = "CgkIyK-AzZcGEAIQBA"; // <GPGSID>
        public const string achievement_rail_gun_levle_8 = "CgkIyK-AzZcGEAIQHg"; // <GPGSID>
        public const string achievement_duck_levle_8 = "CgkIyK-AzZcGEAIQIw"; // <GPGSID>
        public const string achievement_tornado_levle_8 = "CgkIyK-AzZcGEAIQLg"; // <GPGSID>
        public const string achievement_bully_gun_levle_8 = "CgkIyK-AzZcGEAIQIQ"; // <GPGSID>
        public const string achievement_achieved_the_first_100000_kills = "CgkIyK-AzZcGEAIQEg"; // <GPGSID>
        public const string achievement_desert_clear = "CgkIyK-AzZcGEAIQBg"; // <GPGSID>
        public const string achievement_ice_bath_levle_8 = "CgkIyK-AzZcGEAIQKg"; // <GPGSID>
        public const string achievement_blocking_pillow_hall_levle_8 = "CgkIyK-AzZcGEAIQJw"; // <GPGSID>
        public const string achievement_5_card_mix = "CgkIyK-AzZcGEAIQGg"; // <GPGSID>
        public const string achievement_brainberry_levle_8 = "CgkIyK-AzZcGEAIQJA"; // <GPGSID>
        public const string achievement_100_card_mix = "CgkIyK-AzZcGEAIQGw"; // <GPGSID>
        public const string achievement_5_card_draws = "CgkIyK-AzZcGEAIQGA"; // <GPGSID>
        public const string achievement_open_card_number_1 = "CgkIyK-AzZcGEAIQCQ"; // <GPGSID>
        public const string leaderboard_killcnt = "CgkIyK-AzZcGEAIQAw"; // <GPGSID>
        public const string achievement_acquired_card_4 = "CgkIyK-AzZcGEAIQFg"; // <GPGSID>
        public const string achievement_acquired_card_5 = "CgkIyK-AzZcGEAIQFw"; // <GPGSID>
        public const string achievement_level_50_achieved = "CgkIyK-AzZcGEAIQDQ"; // <GPGSID>
        public const string achievement_achieve_the_first_100_kills = "CgkIyK-AzZcGEAIQDw"; // <GPGSID>
        public const string achievement_bumping_bombing_levle_8 = "CgkIyK-AzZcGEAIQIg"; // <GPGSID>
        public const string achievement_acquired_card_1 = "CgkIyK-AzZcGEAIQEw"; // <GPGSID>
        public const string achievement_acquired_card_2 = "CgkIyK-AzZcGEAIQFA"; // <GPGSID>
        public const string achievement_acquired_card_3 = "CgkIyK-AzZcGEAIQFQ"; // <GPGSID>
        public const string achievement_flame_radiation_levle_8 = "CgkIyK-AzZcGEAIQIA"; // <GPGSID>
        public const string achievement_achieving_the_first_1000_kills = "CgkIyK-AzZcGEAIQEA"; // <GPGSID>
        public const string achievement_circular_dora_levle_8 = "CgkIyK-AzZcGEAIQJg"; // <GPGSID>
        public const string achievement_open_only_8_cards = "CgkIyK-AzZcGEAIQCw"; // <GPGSID>
        public const string achievement_reflecting_beet_levle_8 = "CgkIyK-AzZcGEAIQKQ"; // <GPGSID>

}

